"""book model

Revision ID: 63b4af90d1cd
Revises: 8dc8064f7721
Create Date: 2020-04-10 08:45:59.951953

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '63b4af90d1cd'
down_revision = '8dc8064f7721'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amazon_url', sa.Unicode(length=255), nullable=False))
        batch_op.add_column(sa.Column('author', sa.Unicode(length=255), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.Unicode(length=255), nullable=False))
        batch_op.add_column(sa.Column('title', sa.Unicode(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('genre')
        batch_op.drop_column('author')
        batch_op.drop_column('amazon_url')

    # ### end Alembic commands ###
