"""add client model

Revision ID: d72cea6b99d1
Revises: ed2864371744
Create Date: 2020-04-11 11:54:11.555741

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd72cea6b99d1'
down_revision = 'ed2864371744'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_client',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=22), nullable=False),
    sa.Column('secret_key', sa.Unicode(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_client')
    # ### end Alembic commands ###
