"""book model

Revision ID: ed2864371744
Revises: 63b4af90d1cd
Create Date: 2020-04-10 13:25:11.969249

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ed2864371744'
down_revision = '63b4af90d1cd'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
